apiVersion: v1
kind: Pod
metadata:
  name: pod-identity-v1
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
  - name: oaidentity
    image: oaviles/oaidentity:latest
    imagePullPolicy: Always
    env:
    - name: STORAGE_ACCOUNT_NAME
      value: "TYPE HERE YOUR AZURE STORAGE ACCOUNT NAME"
    - name: STORAGE_ACCOUNT_CONTAINER_NAME
      value: "TYPE HERE CONTAINER/FOLDER NAME"